### ISSUE TITLE
caddy好像必须设置超时

### ISSUE THREAD

**Issue by jiuqianyuan** [veekxt/v2ray-template#3]
不设置超时的话，会出现异常tcp链接无法断开的情况

**Comment by veekxt** [comment]
不知道你说的超时具体是指哪些，根据caddy的文档，反代的超时是有默认值的。

没有默认值的超时设置也不会是**必需的**（如果有必要官方则会设置默认值，不是吗），实际上caddy曾经有过一些默认值，但后来删除了，参考 https://github.com/mholt/caddy/issues/1733 

这个模板是想只提供一个**最简化**的配置文件，其余的部分保持默认就好，v2ray也是如此。和其他未列出的配置一样，如果你需要timeout，那么自己添加就好了。

如果你发现默认配置下真的会带来严重问题，请考虑向caddy反馈/讨论。
