### ISSUE TITLE
负载均衡配置

### ISSUE THREAD

**Issue by qinghon** [veekxt/v2ray-template#4]
你好
https://github.com/veekxt/v2ray-template/blob/4577224c867c7ac8deac63c8df8b8241f0d741e3/tcp%2Bvmess%20and%20balance/config.json#L108

这个地方如果配置了多个balancers该如何写呢，有多个tag的话

**Comment by veekxt** [comment]
一个rule对应一个balancer，然后通过selector可以选择多个outbound，在这种设计下，一个rule应该是不需要多个balancer的。
